import React, { forwardRef } from 'react';
import type { SummaryData, GamificationData, UserData } from '../types';

// A helper function to get translations, since this isn't a typical React component with hooks
const getTranslator = (lang: 'en' | 'ar') => {
    const en = {
        "printable": {
            "title": "Strategic Digital Marketing Plan",
            "preparedFor": "Prepared for:",
            "yourTitle": "Your Title:",
            "executiveSummary": "Executive Summary",
            "recommendations": "Goal-Specific Recommendations",
            "analysis": "Strategic Analysis",
            "swot": "SWOT Analysis",
            "persona": "Ideal Customer Persona",
            "keyPriorities": "Key Priorities",
            "keyChannels": "Recommended Channels",
            "metrics": "Metrics for Success",
            "footer": "This strategic plan was generated by an AI-powered system for Elite Qatar."
        }
    };
    const ar = {
        "printable": {
            "title": "خطة التسويق الرقمي الاستراتيجية",
            "preparedFor": "أُعدت لـ:",
            "yourTitle": "لقبك:",
            "executiveSummary": "الملخص التنفيذي",
            "recommendations": "توصيات خاصة بالأهداف",
            "analysis": "التحليل الاستراتيجي",
            "swot": "تحليل SWOT",
            "persona": "شخصية العميل المثالي",
            "keyPriorities": "الأولويات الرئيسية",
            "keyChannels": "القنوات الموصى بها",
            "metrics": "مقاييس النجاح",
            "footer": "تم إنشاء هذه الخطة الاستراتيجية بواسطة نظام مدعوم بالذكاء الاصطناعي لصالح Elite Qatar."
        }
    };

    const translations = lang === 'ar' ? ar : en;

    return (key: string) => {
        const keys = key.split('.');
        let result: any = translations;
        for (const k of keys) {
            result = result?.[k];
            if (result === undefined) return key;
        }
        return result;
    };
};

interface PrintablePlanProps {
    summaryData: SummaryData;
    gamificationData: GamificationData;
    userData: UserData;
    lang: 'en' | 'ar';
}

const PrintablePlan = forwardRef<HTMLDivElement, PrintablePlanProps>(({ summaryData, gamificationData, userData, lang }, ref) => {
    const { executiveSummary, gamification, swotAnalysis, customerPersona, goalRecommendations, keyPriorities, keyChannels, metricsForSuccess } = summaryData;
    const t = getTranslator(lang);
    const dir = lang === 'ar' ? 'rtl' : 'ltr';
    const textAlign = lang === 'ar' ? 'right' : 'left';
    const fontFamily = lang === 'ar' ? "'Tajawal', sans-serif" : "'Bricolage Grotesque', sans-serif";

    const baseStyle: React.CSSProperties = {
        direction: dir,
        textAlign: textAlign,
        fontFamily: fontFamily,
    }

    const sectionStyle: React.CSSProperties = {
        marginBottom: '40px',
        pageBreakInside: 'avoid',
    };

    const h2Style: React.CSSProperties = {
        fontSize: '24px',
        color: '#333',
        borderBottom: '1px solid #ccc',
        paddingBottom: '10px'
    };
    
    const listStyle: React.CSSProperties = {
        listStyleType: 'disc',
        paddingLeft: '20px',
        margin: '10px 0 0'
    };

    return (
        <div ref={ref} style={{ ...baseStyle, width: '800px', padding: '40px', backgroundColor: 'white', color: 'black' }}>
            <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '2px solid #a9ce17', paddingBottom: '20px', marginBottom: '30px' }}>
                <div>
                    <h1 style={{ fontSize: '32px', margin: '0', color: '#333' }}>{t('printable.title')}</h1>
                    <p style={{ fontSize: '18px', margin: '5px 0 0', color: '#555' }}>{t('printable.preparedFor')} <strong>{userData.name}</strong></p>
                    <p style={{ fontSize: '16px', color: '#555' }}>{t('printable.yourTitle')} <span style={{ fontWeight: 'bold', color: '#a9ce17' }}>{gamification.title}</span></p>
                </div>
                 <img 
                    src="https://elite-qatar.net/wp-content/uploads/2023/09/elite-logo-dark.png" 
                    alt="Elite Qatar Logo" 
                    style={{ width: '150px', height: 'auto' }}
                />
            </header>

            <section style={sectionStyle}>
                <h2 style={h2Style}>{t('printable.executiveSummary')}</h2>
                <p style={{ fontSize: '16px', lineHeight: '1.6', color: '#333' }}>{executiveSummary}</p>
            </section>
            
            <section style={sectionStyle}>
                <h2 style={h2Style}>{t('printable.recommendations')}</h2>
                {goalRecommendations.map((rec, index) => (
                    <div key={index} style={{ marginBottom: '20px' }}>
                        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#333' }}>{rec.goal}</h3>
                        <ul style={listStyle}>
                            {rec.recommendations.map((item, i) => (
                                <li key={i} style={{ fontSize: '16px', color: '#555', marginBottom: '5px' }}>{item}</li>
                            ))}
                        </ul>
                    </div>
                ))}
            </section>

            <section style={sectionStyle}>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                    <div>
                        <h2 style={h2Style}>{t('printable.keyPriorities')}</h2>
                        <ul style={listStyle}>
                           {keyPriorities.map((item, i) => <li key={i} style={{ fontSize: '16px', color: '#555', marginBottom: '5px' }}>{item}</li>)}
                        </ul>
                    </div>
                     <div>
                        <h2 style={h2Style}>{t('printable.keyChannels')}</h2>
                        <ul style={listStyle}>
                           {keyChannels.map((item, i) => <li key={i} style={{ fontSize: '16px', color: '#555', marginBottom: '5px' }}>{item}</li>)}
                        </ul>
                    </div>
                </div>
            </section>
             <section style={sectionStyle}>
                <h2 style={h2Style}>{t('printable.metrics')}</h2>
                <ul style={listStyle}>
                   {metricsForSuccess.map((item, i) => <li key={i} style={{ fontSize: '16px', color: '#555', marginBottom: '5px' }}>{item}</li>)}
                </ul>
            </section>


            <section style={sectionStyle}>
                <h2 style={h2Style}>{t('printable.analysis')}</h2>
                <div style={{ display: 'flex', gap: '20px' }}>
                    <div style={{ width: '50%' }}>
                        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#555', marginBottom: '10px' }}>{t('printable.swot')}</h3>
                        {Object.entries(swotAnalysis).map(([key, value]) => (
                            <div key={key} style={{ marginBottom: '10px' }}>
                                <h4 style={{ textTransform: 'capitalize', fontWeight: 'bold' }}>{key}</h4>
                                <ul style={{ listStyleType: 'disc', paddingLeft: '20px', margin: 0 }}>
                                    {/* Fix: Add type guard to ensure value is an array before calling map, as its type is inferred as 'unknown'. */}
                                    {Array.isArray(value) && value.map((item, i) => <li key={i} style={{ fontSize: '14px' }}>{item}</li>)}
                                </ul>
                            </div>
                        ))}
                    </div>
                     <div style={{ width: '50%', border: '1px solid #eee', padding: '15px', borderRadius: '8px' }}>
                        <h3 style={{ fontSize: '18px', fontWeight: 'bold', color: '#555', marginBottom: '10px' }}>{t('printable.persona')}</h3>
                        <h4 style={{ fontSize: '16px', fontWeight: 'bold', margin: '0' }}>{customerPersona.name}</h4>
                        <p style={{ fontSize: '14px', color: '#777', margin: '0 0 10px' }}>{customerPersona.demographics}</p>
                        <h5 style={{ fontWeight: 'bold' }}>Goals:</h5>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '20px', margin: 0 }}>
                            {customerPersona.goals.map((g, i) => <li key={i}>{g}</li>)}
                        </ul>
                        <h5 style={{ fontWeight: 'bold', marginTop: '10px' }}>Pain Points:</h5>
                         <ul style={{ listStyleType: 'disc', paddingLeft: '20px', margin: 0 }}>
                            {customerPersona.painPoints.map((p, i) => <li key={i}>{p}</li>)}
                        </ul>
                    </div>
                </div>
            </section>

            <footer style={{ textAlign: 'center', marginTop: '50px', paddingTop: '20px', borderTop: '2px solid #a9ce17' }}>
                <p style={{ fontSize: '14px', color: '#555' }}>{t('printable.footer')}</p>
                <p style={{ fontSize: '14px', color: '#555' }}>www.elite-qatar.net</p>
            </footer>
        </div>
    );
});

export default PrintablePlan;