import React, { createContext, useState, useContext, useEffect, useCallback } from 'react';

const enTranslations = {
  "welcome": {
    "title": "Design Your Digital Dominance",
    "subtitle": "Unlock a data-driven marketing strategy, tailored to your business goals. Let's build your roadmap to success together.",
    "startButton": "Start Your Journey"
  },
  "header": {
    "bookConsultation": "Book a Consultation",
    "visitWebsite": "Visit Our Website"
  },
  "basicInfo": {
    "title": "Let's Get to Know You",
    "subtitle": "Start by telling us a bit about your business.",
    "contactInfo": "Your Contact Information",
    "namePlaceholder": "Your Name",
    "emailPlaceholder": "Your Email",
    "emailRequired": "Email is required.",
    "emailInvalid": "Please enter a valid email address.",
    "industryTitle": "What's your industry?",
    "subIndustryTitle": "Which sub-industry best describes you?",
    "companySizeTitle": "What's your company size?",
    "welcomeMessage": "Great choice! The {industry} sector is full of potential. Let's find your unique advantage.",
    "continueButton": "Continue"
  },
  "goals": {
    "title": "Define Your Primary Goals",
    "subtitle": "What do you want to achieve? Select one or more."
  },
  "platforms": {
    "title": "Choose Your Digital Arenas",
    "subtitle": "Where will you engage your audience? Select all that apply."
  },
  "challenges": {
    "title": "Identify Your Obstacles",
    "subtitle": "What challenges are you currently facing? Select all that apply.",
    "generateButton": "Generate Full Strategy"
  },
  "summary": {
    "title": "Your Strategic Blueprint is Ready",
    "subtitle": "You are",
    "executiveSummary": "Executive Summary",
    "keyPriorities": "Key Priorities",
    "keyChannels": "Recommended Channels",
    "metricsForSuccess": "Metrics for Success",
    "recommendations": "Goal-Specific Recommendations",
    "swot": "SWOT Analysis",
    "strengths": "Strengths",
    "weaknesses": "Weaknesses",
    "opportunities": "Opportunities",
    "threats": "Threats",
    "persona": "Ideal Customer Persona",
    "personaGoals": "Goals:",
    "personaPainPoints": "Pain Points:",
    "readyTitle": "Ready to Dominate?",
    "readySubtitle": "Your personalized plan is the first step. Let's collaborate to turn this strategy into a market-leading reality.",
    "editButton": "Go Back & Edit",
    "downloadButton": "Download Plan",
    "generatingPDF": "Generating PDF...",
    "bookButton": "Book a Free Strategy Call",
    "roadmap": "Your 12-Month Roadmap",
    "kpi": "Projected KPI Growth",
    "budget": "Budget Allocation",
    "noData": "No data available for this section.",
    "generationError": "An error occurred while generating this section. Please try again.",
    "criticalError": "Our AI is currently facing a connection issue. Please try again later."
  },
  "loading": {
    "title": "Generating Your Future",
    "subtitle": "Our AI is crafting your personalized strategic plan...",
    "live": {
        "summary": "AI is writing the summary...",
        "recommendations": "Tailoring your recommendations...",
        "roadmap": "Building your 12-month roadmap...",
        "kpi": "Projecting KPI growth...",
        "budget": "Allocating your budget...",
        "swot": "Analyzing strengths & weaknesses...",
        "persona": "Creating your customer persona..."
    }
  },
  "navigation": {
    "previous": "Previous",
    "continue": "Continue"
  },
  "share": {
    "text": "I just created a custom digital marketing strategy with Elite Qatar's AI tool! Get your own personalized plan.",
    "title": "My AI-Powered Strategic Plan"
  },
  "printable": {
    "title": "Strategic Digital Marketing Plan",
    "preparedFor": "Prepared for:",
    "yourTitle": "Your Title:",
    "executiveSummary": "Executive Summary",
    "recommendations": "Goal-Specific Recommendations",
    "analysis": "Strategic Analysis",
    "swot": "SWOT Analysis",
    "persona": "Ideal Customer Persona",
    "keyPriorities": "Key Priorities",
    "keyChannels": "Recommended Channels",
    "metrics": "Metrics for Success",
    "footer": "This strategic plan was generated by an AI-powered system for Elite Qatar."
  },
  "email": {
    "subject": "New Strategy Inquiry from {name}",
    "body": "A new client has completed the strategic journey.\n\n--- CLIENT DETAILS ---\nName: {name}\nEmail: {email}\nIndustry: {industry} ({subIndustry})\nCompany Size: {companySize}\n\n--- SELECTED STRATEGY ---\nGoals: {goals}\nChallenges: {challenges}\nPlatforms: {platforms}\n\n--- AI-GENERATED SUMMARY ---\n{summary}\n\n---\nPlease follow up with this lead."
  },
  "contactModal": {
    "title": "Let's Talk Strategy",
    "subtitle": "Choose your preferred way to connect with us.",
    "whatsappButton": "Contact via WhatsApp",
    "emailButton": "Contact via Email"
  },
  "constants": {
    "industries": {
      "tech": "Technology", "ecommerce": "E-commerce", "healthcare": "Healthcare", "finance": "Finance", "realestate": "Real Estate", "education": "Education", "fashion": "Fashion & Apparel", "food": "Food & Beverage"
    },
    "sub_industries": {
      "saas": "SaaS", "fintech": "FinTech", "ai": "AI & ML", "hardware": "Hardware", "retail": "Direct-to-Consumer (D2C)", "marketplace": "Marketplace", "subscription": "Subscription Box", "dropshipping": "Dropshipping", "telehealth": "Telehealth", "medicaldevices": "Medical Devices", "pharma": "Pharmaceuticals", "wellness": "Wellness & Fitness", "banking": "Digital Banking", "investment": "Investment Tech", "insurance": "InsurTech", "crypto": "Crypto & Blockchain", "residential": "Residential", "commercial": "Commercial", "propertymgmt": "Property Management", "proptech": "PropTech", "edtech": "EdTech Platform", "onlinecourses": "Online Courses", "tutoring": "Tutoring Services", "university": "Higher Education", "fastfashion": "Fast Fashion", "luxury": "Luxury Brands", "sustainable": "Sustainable Fashion", "accessories": "Accessories", "restaurant": "Restaurant Chain", "fooddelivery": "Food Delivery", "packagedgoods": "Packaged Goods (CPG)", "healthfood": "Health & Organic Food"
    },
    "company_sizes": {
      "startup": "Startup (1-10)", "smb": "SMB (11-50)", "mid-market": "Mid-Market (51-500)", "enterprise": "Enterprise (500+)"
    },
    "goals": {
      "awareness": "Increase Brand Awareness", "leads": "Generate More Leads", "conversion": "Improve Conversion Rate", "engagement": "Build Community & Engagement", "sales": "Boost Online Sales", "traffic": "Drive Website Traffic"
    },
    "challenges": {
      "budget": "Limited Budget", "competition": "Strong Competition", "tech": "Technical Hurdles", "talent": "Talent Acquisition"
    },
    "platforms": {
      "google": "Google (SEO & SEM)", "instagram": "Instagram", "facebook": "Facebook", "tiktok": "TikTok", "linkedin": "LinkedIn", "x": "X (Twitter)"
    }
  }
};
const arTranslations = {
  "welcome": {
    "title": "صمم هيمنتك الرقمية",
    "subtitle": "اكتشف استراتيجية تسويق تعتمد على البيانات، مصممة خصيصًا لأهداف عملك. لنبني معًا خارطة طريقك نحو النجاح.",
    "startButton": "ابدأ رحلتك"
  },
  "header": {
    "bookConsultation": "احجز استشارة",
    "visitWebsite": "تفضل بزيارة موقعنا"
  },
  "basicInfo": {
    "title": "دعنا نتعرف عليك",
    "subtitle": "ابدأ بإخبارنا القليل عن عملك.",
    "contactInfo": "معلومات التواصل الخاصة بك",
    "namePlaceholder": "اسمك",
    "emailPlaceholder": "بريدك الإلكتروني",
    "emailRequired": "البريد الإلكتروني مطلوب.",
    "emailInvalid": "الرجاء إدخال عنوان بريد إلكتروني صالح.",
    "industryTitle": "ما هو مجالك؟",
    "subIndustryTitle": "أي مجال فرعي يصفك بشكل أفضل؟",
    "companySizeTitle": "ما هو حجم شركتك؟",
    "welcomeMessage": "اختيار رائع! قطاع {industry} مليء بالإمكانيات. لنجد ميزتك التنافسية الفريدة.",
    "continueButton": "متابعة"
  },
  "goals": {
    "title": "حدد أهدافك الأساسية",
    "subtitle": "ما الذي تريد تحقيقه؟ اختر هدفًا أو أكثر."
  },
  "platforms": {
    "title": "اختر ساحاتك الرقمية",
    "subtitle": "أين ستتفاعل مع جمهورك؟ اختر كل ما ينطبق."
  },
  "challenges": {
    "title": "حدد عقباتك",
    "subtitle": "ما هي التحديات التي تواجهها حاليًا؟ اختر كل ما ينطبق.",
    "generateButton": "أنشئ الاستراتيجية الكاملة"
  },
  "summary": {
    "title": "مخططك الاستراتيجي جاهز",
    "subtitle": "أنت",
    "executiveSummary": "الملخص التنفيذي",
    "keyPriorities": "الأولويات الرئيسية",
    "keyChannels": "القنوات الموصى بها",
    "metricsForSuccess": "مقاييس النجاح",
    "recommendations": "توصيات مخصصة لأهدافك",
    "swot": "تحليل SWOT",
    "strengths": "نقاط القوة",
    "weaknesses": "نقاط الضعف",
    "opportunities": "الفرص",
    "threats": "التهديدات",
    "persona": "شخصية العميل المثالي",
    "personaGoals": "الأهداف:",
    "personaPainPoints": "نقاط الألم:",
    "readyTitle": "هل أنت مستعد للهيمنة؟",
    "readySubtitle": "خطتك المخصصة هي الخطوة الأولى. دعنا نتعاون لتحويل هذه الاستراتيجية إلى واقع رائد في السوق.",
    "editButton": "العودة والتعديل",
    "downloadButton": "تحميل الخطة",
    "generatingPDF": "جاري إنشاء PDF...",
    "bookButton": "احجز مكالمة استراتيجية مجانية",
    "roadmap": "خارطة طريقك لمدة 12 شهرًا",
    "kpi": "نمو مؤشرات الأداء الرئيسية المتوقع",
    "budget": "توزيع الميزانية",
    "noData": "لا توجد بيانات متاحة لهذا القسم.",
    "generationError": "حدث خطأ أثناء إنشاء هذا القسم. يرجى المحاولة مرة أخرى.",
    "criticalError": "نواجه حاليًا مشكلة في الاتصال بالذكاء الاصطناعي. يرجى المحاولة مرة أخرى لاحقًا."
  },
  "loading": {
    "title": "جاري صياغة مستقبلك",
    "subtitle": "يقوم الذكاء الاصطناعي لدينا بصياغة خطتك الاستراتيجية المخصصة...",
     "live": {
        "summary": "الذكاء الاصطناعي يكتب الملخص...",
        "recommendations": "جاري تخصيص توصياتك...",
        "roadmap": "جاري بناء خارطة طريقك...",
        "kpi": "جاري توقع نمو المؤشرات...",
        "budget": "جاري تخصيص ميزانيتك...",
        "swot": "جاري تحليل SWOT...",
        "persona": "جاري إنشاء شخصية عميلك..."
    }
  },
  "navigation": {
    "previous": "السابق",
    "continue": "متابعة"
  },
  "share": {
    "text": "لقد أنشأت للتو استراتيجية تسويق رقمي مخصصة باستخدام أداة الذكاء الاصطناعي من Elite Qatar! احصل على خطتك المخصصة.",
    "title": "خطتي الاستراتيجية المدعومة بالذكاء الاصطناعي"
  },
    "printable": {
    "title": "خطة التسويق الرقمي الاستراتيجية",
    "preparedFor": "أُعدت لـ:",
    "yourTitle": "لقبك:",
    "executiveSummary": "الملخص التنفيذي",
    "recommendations": "توصيات خاصة بالأهداف",
    "analysis": "التحليل الاستراتيجي",
    "swot": "تحليل SWOT",
    "persona": "شخصية العميل المثالي",
    "keyPriorities": "الأولويات الرئيسية",
    "keyChannels": "القنوات الموصى بها",
    "metrics": "مقاييس النجاح",
    "footer": "تم إنشاء هذه الخطة الاستراتيجية بواسطة نظام مدعوم بالذكاء الاصطناعي لصالح Elite Qatar."
  },
  "email": {
    "subject": "استفسار استراتيجي جديد من {name}",
    "body": "أكمل عميل جديد الرحلة الاستراتيجية.\n\n--- تفاصيل العميل ---\nالاسم: {name}\nالبريد الإلكتروني: {email}\nالمجال: {industry} ({subIndustry})\nحجم الشركة: {companySize}\n\n--- الاستراتيجية المختارة ---\nالأهداف: {goals}\nالتحديات: {challenges}\nالمنصات: {platforms}\n\n--- ملخص تم إنشاؤه بواسطة الذكاء الاصطناعي ---\n{summary}\n\n---\nيرجى متابعة هذا العميل المحتمل."
  },
    "contactModal": {
    "title": "لنتحدث عن الاستراتيجية",
    "subtitle": "اختر طريقتك المفضلة للتواصل معنا.",
    "whatsappButton": "تواصل عبر واتساب",
    "emailButton": "تواصل عبر البريد الإلكتروني"
  },
  "constants": {
    "industries": {
      "tech": "التكنولوجيا", "ecommerce": "التجارة الإلكترونية", "healthcare": "الرعاية الصحية", "finance": "المالية", "realestate": "العقارات", "education": "التعليم", "fashion": "الأزياء والملابس", "food": "الأغذية والمشروبات"
    },
    "sub_industries": {
      "saas": "برنامج كخدمة (SaaS)", "fintech": "التكنولوجيا المالية (FinTech)", "ai": "الذكاء الاصطناعي والتعلم الآلي", "hardware": "الأجهزة", "retail": "مباشرة إلى المستهلك (D2C)", "marketplace": "سوق إلكتروني", "subscription": "صندوق اشتراك", "dropshipping": "دروبشيبينغ", "telehealth": "الرعاية الصحية عن بعد", "medicaldevices": "الأجهزة الطبية", "pharma": "الأدوية", "wellness": "العافية واللياقة البدنية", "banking": "الخدمات المصرفية الرقمية", "investment": "تكنولوجيا الاستثمار", "insurance": "تكنولوجيا التأمين (InsurTech)", "crypto": "العملات المشفرة والبلوك تشين", "residential": "سكني", "commercial": "تجاري", "propertymgmt": "إدارة الممتلكات", "proptech": "تكنولوجيا العقارات (PropTech)", "edtech": "منصة تكنولوجيا التعليم", "onlinecourses": "دورات عبر الإنترنت", "tutoring": "خدمات الدروس الخصوصية", "university": "التعليم العالي", "fastfashion": "الموضة السريعة", "luxury": "العلامات التجارية الفاخرة", "sustainable": "الأزياء المستدامة", "accessories": "الإكسسوارات", "restaurant": "سلسلة مطاعم", "fooddelivery": "توصيل الطعام", "packagedgoods": "السلع المعبأة (CPG)", "healthfood": "الأغذية الصحية والعضوية"
    },
    "company_sizes": {
      "startup": "شركة ناشئة (1-10)", "smb": "شركة صغيرة ومتوسطة (11-50)", "mid-market": "شركة متوسطة (51-500)", "enterprise": "شركة كبيرة (+500)"
    },
    "goals": {
      "awareness": "زيادة الوعي بالعلامة التجارية", "leads": "توليد المزيد من العملاء المحتملين", "conversion": "تحسين معدل التحويل", "engagement": "بناء مجتمع وتفاعل", "sales": "زيادة المبيعات عبر الإنترنت", "traffic": "زيادة حركة المرور على الموقع"
    },
    "challenges": {
      "budget": "ميزانية محدودة", "competition": "منافسة قوية", "tech": "عقبات تقنية", "talent": "اكتساب المواهب"
    },
    "platforms": {
      "google": "جوجل (SEO و SEM)", "instagram": "انستغرام", "facebook": "فيسبوك", "tiktok": "تيك توك", "linkedin": "لينكد إن", "x": "إكس (تويتر)"
    }
  }
};

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, options?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const loadedTranslations = {
  en: enTranslations,
  ar: arTranslations,
};


// FIX: Removed React.FC to resolve potential type conflicts with framer-motion.
export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
    document.documentElement.dir = dir;
  }, [language]);

  const t = useCallback((key: string, options?: Record<string, any>): string => {
    const keys = key.split('.');
    let result: any = loadedTranslations[language];

    if (!result || Object.keys(result).length === 0) {
      return key; // Return key if translations are not loaded yet
    }
    
    for (const k of keys) {
      result = result?.[k];
      if (result === undefined) {
        return key; // Return key if translation is not found
      }
    }
    
    if (typeof result !== 'string') {
        return key;
    }

    let str = result as string;
    if (options) {
      Object.entries(options).forEach(([optKey, value]) => {
        // Use a regex that matches single curly braces {key} instead of double {{key}}
        str = str.replace(new RegExp(`{${optKey}}`, 'g'), String(value));
      });
    }
    return str;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};